spring.application.name=SpringProject

# Server port
server.port=8080

# Database Config (H2 File)
spring.datasource.url=jdbc:h2:file:./db/blogdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/db-console
spring.h2.console.settings.web-allow-others=false

# Create tables on startup (not for production!)
spring.jpa.hibernate.ddl-auto=create-drop

# Enable lazy loading
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

#Profile photo setting
my.app.photo-prefix=/images/

#Application settings
password.token.reset.timeout.minutes=600
site.domain=http://localhost:8080/

#Email settings
spring.config.import=optional:secret.properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# =============================================================================
# SPRING MAIL CONFIGURATION (SMTP SETTINGS)
# =============================================================================

# @property spring.mail.properties.mail.smtp.auth
# @description Uygulaman?n mail göndermeden önce kullan?c? ad? ve ?ifre ile kimlik do?rulamas? yapmas?n? sa?lar.
# @usage Gmail gibi güvenli sunucular için mutlaka 'true' olmal?d?r.
spring.mail.properties.mail.smtp.auth=true

# @property spring.mail.properties.mail.smtp.starttls.enable
# @description Mevcut bir güvensiz ba?lant?y? TLS (Transport Layer Security) kullanarak güvenli hale getirir.
# @usage Verilerin (?ifre vs.) internet üzerinde aç?k metin olarak gitmesini engellemek için gereklidir.
spring.mail.properties.mail.smtp.starttls.enable=true

# @property spring.mail.properties.mail.smtp.ssl.trust
# @description Uygulaman?n SSL sertifikas? için hangi sunucuya güvenece?ini belirtir.
# @usage 'smtp.gmail.com' yaz?larak sadece Google'?n orijinal sertifikas?na güvenilmesi sa?lan?r; güvenlik duvar? hatalar?n? önler.
spring.mail.smtp.ssl.trust=smtp.gmail.com

# @property spring.mail.protocol
# @description Mail gönderimi s?ras?nda kullan?lacak olan temel ileti?im protokolünü tan?mlar.
# @value 'smtp' (Simple Mail Transfer Protocol) - ?nternet üzerinden e-posta iletimi için standart protokol.
mail.transport.protocol=smtp
